version: '2.1'

services:
  docker-mysql:
    image: alatharn/mysql-springboot-validator
    environment:
    - MYSQL_ROOT_PASSWORD=1234
    - MYSQL_DATABASE=mydb
    - MYSQL_PASSWORD=1234
    volumes:
      - /docker-entrypoint-initdb.d
    healthcheck:
      test: mysql --protocol=socket -hlocalhost -uroot -p1234 -e 'SELECT 1'
  spring-boot-jpa-docker-webapp:
    image: alatharn/springboot-validator
    depends_on:
      docker-mysql:
        condition: service_healthy
    ports:
    - 8081:8081
    environment:
    - DATABASE_HOST=docker-mysql
    - DATABASE_USER=root
    - DATABASE_PASSWORD=1234
    - DATABASE_NAME=mydb
    - DATABASE_PORT=3306
    links:
    - docker-mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 30s
      timeout: 10s
      retries: 5