version: '3'

services:
  docker-mysql:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=1234
    - MYSQL_DATABASE=mydb
    - MYSQL_PASSWORD=1234
  spring-boot-jpa-docker-webapp:
    image: springboot-validator
    depends_on:
    - docker-mysql
    ports:
    - 8081:8081
    environment:
    - DATABASE_HOST=docker-mysql
    - DATABASE_USER=root
    - DATABASE_PASSWORD=1234
    - DATABASE_NAME=mydb
    - DATABASE_PORT=3306